from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


def generate_invoice_pdf(
    invoice_number: str,
    order_number: str,
    customer_name: str,
    customer_phone: str | None,
    customer_city: str | None,
    delivery_city: str | None,
    total_amount: float,
    status: str,
    created_at,
) -> BytesIO:
    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(20 * mm, height - 25 * mm, "KarobarOS")

    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        20 * mm,
        height - 32 * mm,
        "AI-Powered Business Operating System",
    )

    pdf.setFont("Helvetica-Bold", 20)
    pdf.drawRightString(
        width - 20 * mm,
        height - 25 * mm,
        "INVOICE",
    )

    y = height - 55 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Invoice Number:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(55 * mm, y, invoice_number)

    y -= 7 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Order Number:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(55 * mm, y, order_number)

    y -= 7 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Date:")
    pdf.setFont("Helvetica", 10)
    pdf.drawString(
        55 * mm,
        y,
        created_at.strftime("%d %b %Y, %I:%M %p"),
    )

    y -= 15 * mm

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(20 * mm, y, "Bill To")

    y -= 7 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, customer_name)

    y -= 6 * mm

    pdf.setFont("Helvetica", 10)

    if customer_phone:
        pdf.drawString(20 * mm, y, f"Phone: {customer_phone}")
        y -= 6 * mm

    if customer_city:
        pdf.drawString(20 * mm, y, f"City: {customer_city}")
        y -= 6 * mm

    if delivery_city:
        pdf.drawString(20 * mm, y, f"Delivery: {delivery_city}")
        y -= 6 * mm

    y -= 10 * mm

    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(20 * mm, y, "Order Total")

    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawRightString(
        width - 20 * mm,
        y,
        f"Rs. {total_amount:,.2f}",
    )

    y -= 12 * mm

    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(20 * mm, y, "Status:")

    pdf.setFont("Helvetica", 10)
    pdf.drawString(40 * mm, y, status.upper())

    pdf.setFont("Helvetica", 9)
    pdf.drawCentredString(
        width / 2,
        20 * mm,
        "Thank you for doing business with us.",
    )

    pdf.setFont("Helvetica", 8)
    pdf.drawCentredString(
        width / 2,
        14 * mm,
        "Generated by KarobarOS",
    )

    pdf.save()
    buffer.seek(0)

    return buffer
